---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest

resources:
  - name: concourse_demo
    type: git
    source: &repo-source
      uri: https://github.com/Rashmigarg16/Concourse_Demo
      branch: main
  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json

jobs:
  - name: installdependencies
    plan:
      - get: concourse_demo
        trigger: true
      - get: dependency-cache
  - name: runtests
    plan:
      - get: concourse_demo
        trigger: true
        passed: [installdependencies]
      - get: dependency-cache
        passed: [installdependencies]
      - task: runthetestsuite
        file: concourse_demo/ci/tasks/run_tests.yml
